### ISSUE TITLE
ERROR: Kustomize 접근 권한 없음

### ISSUE THREAD

**Issue by phjppo0918** [SOOLZZI/haru-hanjan#7]
```
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:935) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:220) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:186) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:84) ~[kubernetes-client-4.13.2.jar:na]
 at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.getData(ConfigMapPropertySource.java:97) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
 at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.<init>(ConfigMapPropertySource.java:78) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
 at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:96) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
 at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.lambda$locate$0(ConfigMapPropertySourceLocator.java:79) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
 at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
 at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:78) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
 at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) ~[spring-cloud-context-3.1.3.jar:3.1.3]
 at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) ~[spring-cloud-context-3.1.3.jar:3.1.3]
 at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) ~[spring-cloud-context-3.1.3.jar:3.1.3]
 at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:607) ~[spring-boot-2.7.2.jar:2.7.2]
 at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.7.2.jar:2.7.2]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.2.jar:2.7.2]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.2.jar:2.7.2]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.2.jar:2.7.2]
 at com.haruhanjan.alcoholservice.AlcoholServiceApplication.main(AlcoholServiceApplication.java:12) ~[classes/:na]
2022-08-17 02:09:32.945  INFO 1 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-configmap.alcohol-service-config.default'}]
2022-08-17 02:09:33.010  INFO 1 --- [           main] c.h.a.AlcoholServiceApplication          : No active profile set, falling back to 1 default profile: "default"
2022-08-17 02:09:40.214  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=fb3e103c-3c01-338e-8691-bfd6a6f57e51
2022-08-17 02:09:42.811  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-08-17 02:09:42.865  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-08-17 02:09:42.866  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.65]
2022-08-17 02:09:43.566  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-08-17 02:09:43.567  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 10442 ms
2022-08-17 02:09:51.046  WARN 1 --- [//10.96.0.1/...] i.f.k.c.d.i.WatchConnectionManager       : Exec Failure: HTTP 403, Status: 403 - configmaps is forbidden: User "system:serviceaccount:default:default" cannot watch resource "configmaps" in API group "" in the namespace "default"
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
 at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224) ~[okhttp-4.9.3.jar:na]
 at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170) ~[okhttp-4.9.3.jar:na]
 at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.9.3.jar:na]
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
 at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
2022-08-17 02:09:51.099 ERROR 1 --- [           main] .r.EventBasedConfigurationChangeDetector : Error while establishing a connection to watch config maps: configuration may remain stale
io.fabric8.kubernetes.client.KubernetesClientException: configmaps is forbidden: User "system:serviceaccount:default:default" cannot watch resource "configmaps" in API group "" in the namespace "default"
 at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:202) ~[kubernetes-client-4.13.2.jar:na]
 at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592) ~[okhttp-4.9.3.jar:na]
 at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:174) ~[okhttp-4.9.3.jar:na]
 at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.9.3.jar:na]
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
 at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
 Suppressed: java.lang.Throwable: waiting here
  at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:154) ~[kubernetes-client-4.13.2.jar:na]
  at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:341) ~[kubernetes-client-4.13.2.jar:na]
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:820) ~[kubernetes-client-4.13.2.jar:na]
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:793) ~[kubernetes-client-4.13.2.jar:na]
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:84) ~[kubernetes-client-4.13.2.jar:na]
  at org.springframework.cloud.kubernetes.config.reload.EventBasedConfigurationChangeDetector.watch(EventBasedConfigurationChangeDetector.java:74) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
  at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.22.jar:5.3.22]
  at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.22.jar:5.3.22]
  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.22.jar:5.3.22]
  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.2.jar:2.7.2]
  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.2.jar:2.7.2]
  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.2.jar:2.7.2]
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.2.jar:2.7.2]
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.2.jar:2.7.2]
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.2.jar:2.7.2]
  at com.haruhanjan.alcoholservice.AlcoholServiceApplication.main(AlcoholServiceApplication.java:12) ~[classes/:na]
Exception in thread "OkHttp Dispatcher" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2524fb52[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@533b9d9b[Wrapped task = io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2@5b4f3cc5]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@593e10ca[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
 at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
 at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:715)
 at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:714)
 at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.scheduleReconnect(WatchConnectionManager.java:305)
 at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$800(WatchConnectionManager.java:50)
 at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:217)
 at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
 at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:174)
 at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:829)
2022-08-17 02:09:51.196  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 16 endpoint(s) beneath base path '/actuator'
2022-08-17 02:09:51.608  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-08-17 02:09:51.748  INFO 1 --- [           main] c.h.a.AlcoholServiceApplication          : Started AlcoholServiceApplication in 34.411 seconds (JVM running for 39.248)
```

**Comment by phjppo0918** [comment]
![image](https://user-images.githubusercontent.com/55674648/185028523-51d0516b-61c1-4496-aeaa-aecec8a4f0f7.png)

**Comment by phjppo0918** [comment]
2022-08-17 03:28:30.839  WARN 1 --- [           main] o.s.c.k.config.ConfigMapPropertySource   : Can't read configMap with name: [alcohol-service-configmap] in namespace:[default]. Ignoring.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/default/configmaps/alcohol-service-configmap. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. configmaps "alcohol-service-configmap" is forbidden: User "system:serviceaccount:default:default" cannot get resource "configmaps" in API group "" in the namespace "default".
 at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:402) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:384) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:935) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:220) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:186) ~[kubernetes-client-4.13.2.jar:na]
 at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:84) ~[kubernetes-client-4.13.2.jar:na]
 at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.getData(ConfigMapPropertySource.java:97) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
 at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.<init>(ConfigMapPropertySource.java:78) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
 at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:96) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
 at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.lambda$locate$0(ConfigMapPropertySourceLocator.java:79) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
 at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
 at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:78) ~[spring-cloud-kubernetes-config-1.1.10.RELEASE.jar:1.1.10.RELEASE]
 at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) ~[spring-cloud-context-3.1.3.jar:3.1.3]
 at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) ~[spring-cloud-context-3.1.3.jar:3.1.3]
 at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) ~[spring-cloud-context-3.1.3.jar:3.1.3]
 at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:607) ~[spring-boot-2.7.2.jar:2.7.2]
 at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.7.2.jar:2.7.2]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.2.jar:2.7.2]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.2.jar:2.7.2]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.2.jar:2.7.2]
 at com.haruhanjan.alcoholservice.AlcoholServiceApplication.main(AlcoholServiceApplication.java:12) ~[classes/:na]

**Comment by phjppo0918** [comment]
![Uploading image.png…]()

드디어 해따...
